# Kubernetes files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-deployment
  namespace: production
  labels:
    app: cv
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv
      version: "1.0"
  template:
    metadata:
      labels:
        app: cv
        version: "1.0"
    spec:
      containers:
        - name: cv
          image: mauriballes/cv:1.0
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 102Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cv-service
  namespace: production
spec:
  selector:
    app: cv
    version: "1.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cv-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: cv.mauriballes.com
      http:
        paths:
          - path: /
            backend:
              serviceName: cv-service
              servicePort: 80
