# Kubernetes files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-deployment
  namespace: production
  labels:
    app: cv
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv
      version: "1.0"
  template:
    metadata:
      labels:
        app: cv
        version: "1.0"
    spec:
      containers:
        - name: cv
          image: mauriballes/cv:1.0
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 102Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cv-service
  namespace: production
spec:
  selector:
    app: cv
    version: "1.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cv-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`cv.mauriballes.com`) && PathPrefix(`/`)
      priority: 0
      services:
        - kind: Service
          name: cv-service
          port: 80
